name: Build Windows VST3

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    # 1. Pobranie Twojego kodu z GitHuba
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Pobranie frameworka JUCE (brakuje go w repozytorium, a CMake go wymaga)
    - name: Clone JUCE
      run: git clone https://github.com/juce-framework/JUCE.git JUCE

    # 3. Konfiguracja projektu przy użyciu CMake
    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022"

    # 4. Właściwa kompilacja wtyczki w trybie Release
    - name: Build Plugin
      run: cmake --build build --config Release

    # 5. Spakowanie i udostępnienie gotowego pliku .vst3 do pobrania
    - name: Upload VST3 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DRUM_SAT_76-Windows-VST3
        path: build/DRUM_SAT_76_artefacts/Release/VST3/DRUM_SAT_76.vst3
   # 5. Uruchomienie Inno Setup w celu stworzenia instalatora .exe
    - name: Build Windows Installer
      uses: minic/inno-setup-action@v1.2.2
      with:
        path: installer.iss

    # 6. Spakowanie i udostępnienie gotowego instalatora .exe do pobrania
    - name: Upload Windows Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DRUM_SAT_76-Windows-Installer
        path: DRUM_SAT_76_Windows_Installer.exe
